apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hackathon-deployment
  labels:
    app: hackathon
spec:
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
        - name: app-hackathon-container
          image: 807550779778.dkr.ecr.us-east-1.amazonaws.com/fiap-hackathon
          ports:
            - containerPort: 80
          env:
            - name: POSTGRE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-hackathon-opaque
                  key: POSTGRE_CONNECTION_STRING
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-hackathon-config
                  key: ASPNETCORE_ENVIRONMENT
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 400m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-hackathon-config
data:
  ASPNETCORE_ENVIRONMENT: "DEVELOPMENT"
